### ISSUE TITLE
XML parsing error [ plugin.js -> _getNodeFromHtml (if) ]

### ISSUE THREAD

**Issue by 0x539-nero** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#84]
Problems with XML parsing when I bring in a table from excel into Internet Explorer. Then I click "Save Page" and the error **XML parsing error [ plugin.js -> _getNodeFromHtml (if) ]** shows up.

This error does not occur when I copy and paste from excel into chrome.

Anyone have a fix?

IE Version: IE 11.0.9600.18314

**Comment by riparap** [comment]
Can you test this with your IE-browser: (Wysiwyg Version 1.5.6_0 [B551+11.06.2016]), - temporarily comment out lines 1433 - 1443 in mediawiki/plugin.js, save the file, clear cache of your browser and copy - paste your Excel table, does this fix the problem with IE?

**Comment by 0x539-nero** [comment]
I             } catch (e) { // 16.01.15 RL
                // not well-formed text raises an exception in IE from version 9, others let it continue
                alert ("XML parsing error [ plugin.js->_getNodeFromHtml (if) ]");
                return false;
            };

It was uncommented when I opened it up.

**Comment by 0x539-nero** [comment]
I commented it and yes, the error went away but when I click save then nothing saves (Only in IE, chrome works)

**Comment by 0x539-nero** [comment]
Here is my step to get this error:
- I create a page and bring in an excel table with chrome.
- I bring in the same table from excel with IE.
- I go to the page.

Then the parser error comes.

Warning: Missing argument 2 for Parser::makeFreeExternalLink(), called in /var/www/html/wiki.mysite.com/extensions/WYSIWYG/CKeditorParser.body.php on line 250 and defined in /var/www/html/wiki.mysite.com/includes/parser/Parser.php on line 1470

Notice: Undefined variable: numPostProto in /var/www/html/wiki.mysite.com/includes/parser/Parser.php on line 1511

in /var/www/html/wiki.mysite.com/includes/WebResponse.php on line 37

**Comment by 0x539-nero** [comment]
Anything on this?

**Comment by riparap** [comment]
This is caused by one of the regex commands used to clean html data of page when wysiwyg to wikitext conversion is made.That regexec command corrupts html code in IE causing the symptoms you found.

Error is caused by this:
`data = data.replace(/<col[^>]*>/gi, '' );`

It works with paste result of excel table, where there is orphaned `<col>` tag left after paste 
`...<col width="64" style="width;48pt;">`
by removing it completely,

But it corrupts this kind of result of paste where there is valid `colgroup` tags available
`...<colgroup><col width="64" style="width;48pt;"></colgroup>...`
leaving ending tag `</colgroup>` left.

So if I change regexec to be like this (added space after string col)
`data = data.replace(/<col [^>]*>/gi, '' );`
problem seems to be solved  (=>Version 1.5.6_0 [B551+25.06.2016])  (**EDITED:** This did not solve the case, see comments below). 

However I am not sure in what way paste action of Excel table defines `<col>` and `<colgroup>` tags so it may be that with different paste result it still may cause errors.

Does anybody know better regexeg solution to delete orphaned `<col ....>` tag but leaving valid `<colgroup>...</colgroup>` tags intact?

**Comment by 0x539-nero** [comment]
Am I doing something wrong? I updated my code but when I save it does not save the data I have copy and pasted from Excel. 

Also another thing that I noticed when I paste from Excel is that when I press "Source" it just grey's out the button and it won't show the source.

**Comment by Serze** [comment]
Also another thing that I noticed when I paste from Excel is that when I press "Source" it just grey's out the button and it won't show the source.

**Comment by riparap** [comment]
In my test I used excel2016 installed on local computer. Test data was simple 3x3 cells area where there were number 12345 in the middle cell.

As I wrote in my earlier post result of copy-paste operation may depend on contents of data you are pasting. How "massive" paste operation are you trying to do... can you perhaps share your excel table so that I can do tests using it? .... or provide information what does your table contain (..formats, fomulas etc...). What versions of Excel are you using?

**Comment by 0x539-nero** [comment]
Any excel table is struggling. It does not contain any formulas in it. I will post my example tommorow. Thank you for helping.

Is there anyway I can turn a debugger on for you?

**Comment by riparap** [comment]
Debug mode of mediawiki does not help, I need sample of the case where paste fails.

Have you tried this: create new workbook in Excel, in center of area of 3x3 cells place some number, f.ex 12345. Copy that area of 3x3 cells and paste it in empty new page of wysiwyg and save the page. Does this fail in your environment?

What version of Excel are you using?

**Comment by 0x539-nero** [comment]
So now when I tried today it works if I make a 3x3 with 12345 in the middle.

The problem happens when you try to copy and paste excel files that have their column width changed.

If the column width is default it will paste successfully. If you have changed the width of one column it will throw out the "XML parsing error [ plugin.js -> _getNodeFromHtml (if) ]" error.

**Comment by riparap** [comment]
Can you try this:  in `mediawiki/plugin.js` replace the line (there is one space after `col`)
`data = data.replace(/<col [^>]*>/gi, '' );` 
with these two lines
`data = data.replace(/<colgroup>.*<\/colgroup>/gi, '' );`
`data = data.replace(/<col[^>]*>/gi, '' );`

**Comment by 0x539-nero** [comment]
I have edited starting on line 1410 of 2636:

```
    //data = data.replace(/<col [^>]*>/gi, '' ); 
data = data.replace(/.<\/colgroup>/gi, '' ); 
``data = data.replace(/]>/gi, '' );
```

Is this correct? I am still receiving the same error.

**Comment by riparap** [comment]
If your paste result of code here is what you have in plugin.js, it is not right at all. Check that  you do not have anything extra in the beginning or end of lines you copied here (there may be markup commands of this page in your paste result). 

In your  code editor new lines should look like this:
`data = data.replace(/<colgroup>.*<\/colgroup>/gi, '' );`
`data = data.replace(/<col[^>]*>/gi, '' );`

After modification of plugin.js, you have to empty cache of your browser first before you do anything else, otherwise  browser will use old file which it has in memory.

Again, do the copy - paste test of excel data into blank page of mediawiki using data of simple 3x3 cells.

**Comment by 0x539-nero** [comment]
Is it supposed to have a `` before data?

``data = data.replace(/]>/gi, '' );

**Comment by Serze** [comment]
My code is:

		//   Prev. works with this: ...<col width="64" style="width;48pt;">... removing it completely,
		//   but it corrupts this:  ...<colgroup><col width="64" style="width;48pt;"></colgroup>... leaving ending tag </colgroup> left
        data = data.replace(/.<\/colgroup>/gi, '' ); 
	data = data.replace(/]>/gi, '' );

I have cleared the cache and now when I put anything in (just a default width on a 3x3 excel) it shoots the "XML parsing error [ plugin.js -> _getNodeFromHtml (if) ]" error.

**Comment by riparap** [comment]
No it is not right..... compare lines in your code editor to two lines you see here abowe in my comment, if your lines do not match, edit them manually in your code editor so that they do match what you can see here.

**Comment by 0x539-nero** [comment]
BOOM! Success!

**Comment by 0x539-nero** [comment]
How do I go about thanking you!!!

**Comment by 0x539-nero** [comment]
Alright we are set and good to go sir. Hopefully my little implementation of the += in WYSIWYG.php was enough to make up for this :D

**Comment by riparap** [comment]
Good to hear that it works. It is not pullet proof solution and may still fail depending on what kind of data paste from Excel produces.

I will include this fix in next update.

**Comment by 0x539-nero** [comment]
I really do appreciate all of the help.

**Comment by riparap** [comment]
I think I found a better solution which will keep valid colgroup- tags:
`data = data.replace(/<col[ >][^<\/]*/gi, '' );`
`data = data.replace(/<\/col>/gi, '' );`

This has been included in branch wysiwyg_mw127 Version 1.5.6_0 [B551+01.07.2016].

**Comment by nauman5** [comment]
I have been using WYSIWYG version 1.5.6_0 [B551+08.07.2016] and CKEditor 4.5.8 rev c1fc9a9 with MediaWiki 1.26.2 and it was working fine. After upgrading to version [B551+09.11.2016], I have started receiving error **XML parsing error [ plugin.js -> _getNodeFromHtml (if) ]**  while editing some existing pages, when I press [Show WikiTestEditor]. I was receiving this error in previous version as well but later on it was resolved (I don't remember how). I'd appreciate any help in resolving this issue. Regards, Nauman

**Comment by riparap** [comment]
If you have had same problem with the previous version  [B551+08.07.2016] you were using, then problem was not resolved by modifications of wysiwyg, you must have changed something with the contents of your wiki page or done something else. Have your tried if browser type has some effect on this (IE, FF and Chrome)? 

All newer versions than your previous used one, contain major modifications  how contents of page is handled by editor. In order to solve this issue you should be able to pinpoint your issue to problematic contents of page and provide example of wikitext which is causing your problem. To find part causing this issue, perhaps you could make a copy of the page and strip it down part by part until it works properly.

**Comment by nauman5** [comment]
@riparap, Thank you for your response. I have figured out that the error is caused due to the presence of long dash or en dash character (–) in my wiki page, which is wider than hyphen and can be printed on screen using the combination Alt 0150. Once I remove this character from the page, parsing error goes away. Previous version [B551+08.07.2016] accepts long dash and does not cause parsing error even if page contains long dash. 

Reason for presence of this character in my code is notepad++ which I use for code editing. I think notepad++ inserts long dashes instead of hyphens or may be hyphens are changed to long dashes when I copy the code from notepad++ and paste in the Wiki editor.

Also I am facing couple of more issues and would appreciate your help
a) I need to click twice on the toggle button to switch between the editors. Single click does not switch the view. Previous version was fine.
b) I am using extension MSUpload version 10.3. File drag and drop area / toolbar is not visible when I use WYSIWYG. However it is visible when I use only WikiEditor alone without WYSIWYG,

**Comment by riparap** [comment]
What browser version are you using? In my test long dash alone is not causing any problems, It must be something else or then combination with something else. Try creating new page where you copy your problematic text alone trying to keep amount of text as little as possible so that will still create error and then copy-paste that wikitext here.

PS. I would appreciate if you create issue / problem here, in case your problem is not related to header of the current one. Having more than one problems listed under same issue header here is very confusing and makes tracking errors and their solutions difficult.

**Comment by nauman5** [comment]
I am using IE11 [Version 11.0.9600.18449, Update Versions: 11.0.35 (KB3185319)]. 
I tried in the new page with nothing else except long dash and I still get the same error. I have following settings in my localSettings.php

wfLoadExtension( 'WYSIWYG' ); 
$wgGroupPermissions['*']['wysiwyg'] = true;
$wgDefaultUserOptions['cke_show'] = 'richeditor';    //Enable CKEditor
$wgDefaultUserOptions['riched_use_toggle'] = true;  //Editor can toggle CKEditor/WikiText
$wgDefaultUserOptions['riched_start_disabled'] = false; //Important!!! else bug...
$wgDefaultUserOptions['riched_toggle_remember_state'] = true; //working/bug?
$wgDefaultUserOptions['riched_use_popup'] = false;   //Deprecated

$wgFCKEditorExcludedNamespaces[] = NS_MEDIAWIKI;
$wgFCKEditorExcludedNamespaces[] = NS_TEMPLATE;

$wgFCKEditorSpecialElementWithPreTag   = 0;
$wgFCKEditorSpecialElementWithTextTags = 0;

wfLoadExtension( 'WikiEditor' );
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;
$wgDefaultUserOptions['wikieditor-publish'] = 1;

**Comment by riparap** [comment]
Seems that this has not any effect, I have these disabled:
`$wgDefaultUserOptions['wikieditor-preview'] = 0;`
`$wgDefaultUserOptions['wikieditor-publish'] = 0;`

With MW 1.27.0 and Chrome long dash seems to work ok.
I have also tried MW 1.27.0 and MW 1,26,2 with FF and long dash works ok.
I have tried MW 1.27.0 and MW 1.26.2 with IE and it seems to fail as you have told. I will try to test why it fails like that...

**Comment by riparap** [comment]
IE seems to use html entities instead of characters as FF and Chrome do. I added ndash- entity into conversion list. This has been fixed in version 1.5.6_0 [B551+22.11.2016].

**Comment by nauman5** [comment]
Thank you. I appreciate your help

**Comment by riparap** [comment]
nauman5: _a) I need to click twice on the toggle button to switch between the editors. Single click does not switch the view. Previous version was fine._

Do you mean the source- button or the toggle link if it has been enabled? 
If you are referring to toggle- link, it may be some kind of focus issue of link. Try moving pointer away from link so that focus is somewhere else (click elsewhere) and then click the toggle- link.

If you are referring to source- button of CKeditor window, then I have never experienced that there has been any problem with the button itself. Problems have usually been with conversion that should happen as result, it either works or then it fails if there are some issues with contents of page.

**Comment by nauman5** [comment]
I meant the toggle link and you are right it seems to be the focus issue. if I click somewhere else and then click back on the toggle-link, it works fine.

**Comment by riparap** [comment]
I do not know how that could be changed. That link is "link" and there should not be anything special about it.
